Repository mm-ninja-turtles/turtle-express, pull requests merged in 2022-08, with the labels that each got.

#10 Fixing Fastify url in README.md
  README.md
Labels: documentation

#11 Feature lifecycle
  .prettierrc
  examples/express-ts/index.ts
  lib/create-handler.ts
  lib/create-path.ts
  lib/handler-function-steps.ts
  package.json
Labels: enhancement

#12 fix(create-handler): 🐞 response validation possible undefined
  examples/express-ts/index.ts
  lib/create-handler.ts
Labels: bug

#18 fix(create-handler): 🐞 remove response from resolver func options, router accept json, urlencoded
  examples/express-ts/index.ts
  lib/create-handler.ts
  lib/create-router.ts
Labels: type: bug

#19 feat(error-format): 🎉 run format func on zod validation
  examples/express-ts/index.ts
  lib/create-handler.ts
Labels: type: enhancement

#21 feat(resolver): 🎉 new uncontrolledResolver options in handler func
  examples/express-ts/index.ts
  lib/create-handler.ts
  lib/create-path.ts
  lib/handler-function-steps.ts
Labels: type: enhancement

#25 feat(fetch): 🎉 integrate with cross-fetch to global for fetch support
  examples/express-ts/index.ts
  examples/express-ts/paths/_index.ts
  examples/express-ts/paths/custom-resolver.ts
  examples/express-ts/paths/fetch-api.ts
  examples/express-ts/paths/guard.ts
  examples/express-ts/paths/hello/index.ts
  examples/express-ts/paths/hello/name.ts
  examples/express-ts/paths/request-validation.ts
  examples/express-ts/paths/validation.ts
  examples/express-ts/router.ts
  lib/index.ts
  package.json
  pnpm-lock.yaml
Labels: type: enhancement

#26 chore(package-name): 🍰 new package name turtle-express
  package.json
Labels: type: refactor

#34 Update the title in README.md
  README.md
Labels: type: documentation

#38 docs(readme): 📚 clarify about `turtle-express` in main readme
  README.md
Labels: type: documentation
